using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using System.IO;


namespace ConsoleApplication4
{
    class Program
    {
        static void Main(string[] args)
        {
            {
                if (args.Length == 0)
                    return; // return if no file was dragged onto exe
                const string quote = "\"";

                string inputPath = Path.GetFileName(args[0]);
                string extension = Path.GetExtension(inputPath);
                if (extension != ".txt")
                {
                    return; // return if file is not txt
                }


                string path;
                path = Path.GetDirectoryName(args[0])
               + Path.DirectorySeparatorChar
               + Path.GetFileNameWithoutExtension(args[0]);
                string cfgpath = path + ".cfg";
                string txtpath = path + ".txt";



                string name = Path.GetFileNameWithoutExtension(args[0]);
                System.Text.StringBuilder sb = new System.Text.StringBuilder();
                StreamReader reader = File.OpenText(txtpath);

                string newLine = Environment.NewLine;
                StringSplitOptions splitOptions = StringSplitOptions.RemoveEmptyEntries;

                string[] inputLines = File.ReadAllText(txtpath, Encoding.GetEncoding(1251)).Split(new string[] { newLine }, splitOptions);

                sb.Append("// Generated by Ostrich's TXT to CFG converter");

                File.WriteAllText(cfgpath, sb.ToString());

                int i = 0;

                do
                {
                    sb.Append("alias " + name + i + " " + quote + "say " + inputLines[i] + quote + Environment.NewLine);
                    i++;

                } while (i < inputLines.Length);

                File.WriteAllText(cfgpath, sb.ToString());

                sb.Append("alias w " + quote + "wait 300" + quote + Environment.NewLine);

                File.WriteAllText(cfgpath, sb.ToString());


                int linesNumber = inputLines.Count();

                sb.Append("alias " + name + " " + quote);

                List<string> lastLine = new List<string>();

                int b = 0;
                do
                {
                    string buffer = name + b + "; " + "w" + "; ";
                    lastLine.Add(buffer);
                    b++;
                } while (b <= linesNumber && b >= 0);

                string lastLineToWrite = String.Join(String.Empty, lastLine.ToArray());

                sb.Append(lastLineToWrite + quote);

                File.WriteAllText(cfgpath, sb.ToString());

                if (lastLineToWrite.Length > 510)
                {
                    Console.WriteLine("Oops. The last line length is {0} characters, that is more than 510 characters that one console line may have.", lastLineToWrite.Length);
                    Console.WriteLine("Try to rename your text file to a shorter name or to remove some lines of the text.");
                    Console.WriteLine("Press any key to exit...");
                    File.Delete(cfgpath);
                    Console.ReadKey();
                    
                    return;
                }



                Console.WriteLine("Sucsess!");
                Console.WriteLine("Output was written to {0}", cfgpath);
                Console.WriteLine("Press any key to exit...");
                Console.ReadKey();




            }


        }


    }
        }

