using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using System.IO;


namespace ConsoleApplication4
{
    class Program
    {
        static void Main(string[] args)
        {
            {
                if (args.Length == 0)
                    return; // return if no file was dragged onto exe
                const string quote = "\"";

                string inputPath = Path.GetFileName(args[0]);
                string extension = Path.GetExtension(inputPath);
                if (extension != ".txt")
                {
                    return; // return if file is not txt
                }


                string path;
                path = Path.GetDirectoryName(args[0])
               + Path.DirectorySeparatorChar
               + Path.GetFileNameWithoutExtension(args[0]);
                string cfgpath = path + ".cfg";
                string txtpath = path + ".txt";

                string name = Path.GetFileNameWithoutExtension(args[0]);
                System.Text.StringBuilder sb = new System.Text.StringBuilder();
                StreamReader reader = File.OpenText(txtpath);

                string newLine = Environment.NewLine;
                StringSplitOptions splitOptions = StringSplitOptions.RemoveEmptyEntries;

                string[] inputLines = File.ReadAllText(txtpath, Encoding.GetEncoding(1251)).Split(new string[] { newLine }, splitOptions);

                sb.Append("// Generated by Ostrich's TXT to CFG converter" + Environment.NewLine);

                File.WriteAllText(cfgpath, sb.ToString());

                int i = 1;

                do
                {
                    sb.Append("alias " + name + i + " " + quote + "say " + inputLines[i] + quote + "; alias " + name + " " + name + ++i + "; wait 300; " + name + quote + Environment.NewLine);

                } while (i < inputLines.Length-1);
                sb.Append("alias " + name + i + " " + quote + "say " + inputLines[i] + quote + Environment.NewLine);


                sb.Append("alias " + name + " " + name + "1" + Environment.NewLine);

                File.WriteAllText(cfgpath, sb.ToString());

 
                
                Console.WriteLine("Sucsess!");
                Console.WriteLine("Output was written to {0}", cfgpath);
                Console.WriteLine("Press any key to exit...");
                Console.ReadKey();




            }


        }


    }
        }

